# Generated by Django 4.0.4 on 2022-04-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
    ]
